/**
 * The public emerging-technology taxonomy.
 *
 * Written for this repository. Each topic carries keywords the classifier matches against
 * post text, plus a definition and two boundary cases kept for the result page and for
 * anyone auditing why a post matched.
 *
 * Matching is deliberately deterministic: the same post always produces the same topics, a
 * curious participant can be shown exactly which words matched, and nothing here needs a
 * network call or a credit balance. Versioned, because changing the keywords changes what
 * past scores meant.
 */

export type Topic = {
  readonly id: string;
  readonly label: string;
  /** Two words at most. Full labels do not fit a projector row or a result card. */
  readonly short: string;
  readonly definition: string;
  readonly counts: string;
  readonly doesNotCount: string;
  /** Lowercase. Matched on word boundaries, so "zk" never fires inside "zkSync-adjacent". */
  readonly keywords: readonly string[];
};

export const TAXONOMY_VERSION = '1.2.0';

export const TAXONOMY: readonly Topic[] = [
  {
    id: 'cryptography',
    label: 'Cryptography and zero-knowledge',
    short: 'Cryptography',
    definition: 'Proof systems, encryption, signatures, and the assumptions they rest on.',
    counts: 'Explaining why a trusted setup needs no single party to hold the toxic waste.',
    doesNotCount: 'Announcing that a project "uses ZK" without saying what it proves.',
    keywords: [
      'encryption',
      'private key',
      'public key',
      'signature',
      'hash',
      'proof system',
      'verifier',
      'prover',
      'zk',
      'zero knowledge',
      'zero-knowledge',
      'snark',
      'stark',
      'plonk',
      'trusted setup',
      'elliptic curve',
      'hash function',
      'signature scheme',
      'merkle',
      'commitment scheme',
      'homomorphic',
      'cryptography',
      'cryptographic',
      'preimage',
      'nullifier',
    ],
  },
  {
    id: 'consensus',
    label: 'Consensus and distributed systems',
    short: 'Consensus',
    definition: 'Agreement protocols, replication, fault tolerance, and their failure modes.',
    counts: 'Describing how a synchrony assumption changes a protocol’s liveness guarantee.',
    doesNotCount: 'Reporting that a chain had an outage, with no account of why.',
    keywords: [
      'blockchain',
      'validator',
      'node',
      'block time',
      'epoch',
      'staking',
      'stake',
      'decentraliz',
      'network upgrade',
      'consensus',
      'byzantine',
      'bft',
      'finality',
      'fork choice',
      'validator',
      'proof of stake',
      'proof of work',
      'liveness',
      'safety',
      'synchrony',
      'gossip',
      'replication',
      'raft',
      'paxos',
      'slashing',
      'reorg',
    ],
  },
  {
    id: 'scaling',
    label: 'Blockchain infrastructure and scaling',
    short: 'Scaling',
    definition: 'Execution, data availability, rollups, state growth, and node operation.',
    counts: 'Arguing that data availability, not execution, is the binding constraint.',
    doesNotCount: 'Posting a throughput number with no method behind it.',
    keywords: [
      'web3',
      'solana',
      'ethereum',
      'bitcoin',
      'polygon',
      'arbitrum',
      'base ',
      'sui ',
      'aptos',
      'mainnet',
      'testnet',
      'devnet',
      'bridge',
      'cross-chain',
      'crosschain',
      'gas fee',
      'transaction',
      'onchain',
      'on-chain',
      'block space',
      'rollup',
      'layer 2',
      'l2',
      'data availability',
      'calldata',
      'blob',
      'sharding',
      'throughput',
      'tps',
      'state growth',
      'execution layer',
      'sequencer',
      'optimistic rollup',
      'validium',
      'state root',
      'archive node',
      'full node',
    ],
  },
  {
    id: 'smart-contracts',
    label: 'Smart contracts and on-chain programming',
    short: 'Contracts',
    definition: 'Contract languages, virtual machines, upgrade patterns, and gas behaviour.',
    counts: 'Explaining what EIP-7702 changes about how an EOA can act.',
    doesNotCount: 'Sharing a contract address with no explanation.',
    keywords: [
      'smart contract',
      'token',
      'program',
      'deploy',
      'contract',
      'anchor',
      'spl',
      'mint',
      'nft',
      'dapp',
      'smart contract',
      'solidity',
      'evm',
      'opcode',
      'gas limit',
      'abi',
      'erc-20',
      'erc20',
      'erc-721',
      'erc721',
      'eip-',
      'proxy pattern',
      'reentrancy',
      'calldata',
      'precompile',
      'bytecode',
      'foundry',
      'hardhat',
      'anchor program',
    ],
  },
  {
    id: 'ml-systems',
    label: 'Machine learning systems',
    short: 'ML systems',
    definition: 'Training, inference, serving, and the engineering that makes them work.',
    counts: 'Explaining why the slowest node sets the pace in synchronous training.',
    doesNotCount: 'Sharing a benchmark leaderboard screenshot without interpretation.',
    keywords: [
      'model',
      'training',
      'dataset',
      'neural',
      'transformer',
      'inference',
      'weights',
      'parameters',
      'training run',
      'fine-tune',
      'fine tune',
      'gradient',
      'backprop',
      'checkpoint',
      'gpu cluster',
      'cuda',
      'distributed training',
      'batch size',
      'learning rate',
      'inference server',
      'quantiz',
      'distill',
      'tensor',
      'epoch',
    ],
  },
  {
    id: 'language-models',
    label: 'Language models and applied AI',
    short: 'AI models',
    definition: 'Model behaviour, prompting, evaluation, fine-tuning, and cost control.',
    counts: 'Showing how caching a stable prompt prefix cut inference cost, and why.',
    doesNotCount: 'Reacting to a model release with no claim about what changed.',
    keywords: [
      'machine learning',
      'genai',
      'agent',
      'ai ',
      'artificial intelligence',
      'chatgpt',
      'claude',
      'gpt-',
      'openai',
      'anthropic',
      'copilot',
      'assistant',
      'llm',
      'language model',
      'system prompt',
      'tokenizer',
      'context window',
      'embedding',
      'temperature',
      'hallucinat',
      'rag',
      'retrieval augmented',
      'system prompt',
      'few-shot',
      'chain of thought',
      'eval harness',
      'benchmark',
    ],
  },
  {
    id: 'agents',
    label: 'AI agents and tooling',
    short: 'Agents',
    definition: 'Tool use, orchestration, evaluation harnesses, and agent failure modes.',
    counts: 'Explaining why non-deterministic tool naming breaks an agent chain.',
    doesNotCount: 'Demoing an agent with no account of what it does when it fails.',
    keywords: [
      'automation',
      'bot ',
      'pipeline',
      'integration',
      'orchestration',
      'ai agent',
      'tool use',
      'tool call',
      'function calling',
      'orchestrat',
      'mcp',
      'autonomous',
      'harness',
      'subagent',
      'agentic loop',
      'workflow engine',
    ],
  },
  {
    id: 'data',
    label: 'Data engineering and retrieval',
    short: 'Data',
    definition: 'Pipelines, indexes, vector search, and the quality of what comes back.',
    counts: 'Comparing recall at fixed latency across vector databases, with method.',
    doesNotCount: 'Naming a database as a favourite with no comparison.',
    keywords: [
      'database',
      'analytics',
      'metrics',
      'dashboard',
      'api ',
      'endpoint',
      'json',
      'backend',
      'vector database',
      'vector db',
      'inverted index',
      'embedding',
      'recall',
      'pipeline',
      'etl',
      'postgres',
      'sql query',
      'query plan',
      'sharded',
      'cache hit',
      'warehouse',
      'dataset',
      'schema migration',
    ],
  },
  {
    id: 'security',
    label: 'Security and auditing',
    short: 'Security',
    definition: 'Vulnerability classes, verification, threat models, and post-mortems.',
    counts: 'A post-mortem tracing an outage to a retry loop with no jitter.',
    doesNotCount: 'Announcing that an audit was passed.',
    keywords: [
      'exploit',
      'hack',
      'rug',
      'scam',
      'phishing',
      'secure',
      'safety',
      'bug ',
      'incident',
      'vulnerab',
      'exploit',
      'security audit',
      'cve',
      'attack surface',
      'threat model',
      'post-mortem',
      'postmortem',
      'root cause',
      'fuzz',
      'formal verification',
      'overflow',
      'injection',
      'sandbox',
      'supply chain',
    ],
  },
  {
    id: 'devtools',
    label: 'Developer tooling and languages',
    short: 'Dev tooling',
    definition: 'Compilers, type systems, build systems, testing, and language design.',
    counts: 'Explaining what a type system change makes impossible to express.',
    doesNotCount: 'Stating a language preference with no reasoning.',
    keywords: [
      'open source',
      'repo',
      'github',
      'library',
      'framework',
      'docs',
      'developer',
      'engineering',
      'code',
      'build',
      'compiler',
      'type system',
      'rust',
      'typescript',
      'golang',
      'linter',
      'build system',
      'ci/cd',
      'monorepo',
      'test suite',
      'refactor',
      'api design',
      'sdk',
      'codegen',
      'borrow checker',
    ],
  },
  {
    id: 'performance',
    label: 'Hardware and performance',
    short: 'Performance',
    definition: 'Latency, throughput, memory behaviour, and the measurement of them.',
    counts: 'Arguing that time-to-first-token matters more to users than tokens per second.',
    doesNotCount: 'Posting a speed claim with no baseline.',
    keywords: [
      'speed',
      'fast',
      'slow',
      'scale',
      'efficient',
      'optimization',
      'throughput',
      'latency',
      'throughput',
      'benchmark',
      'p50',
      'p95',
      'p99',
      'memory footprint',
      'allocation',
      'profil',
      'cache hit rate',
      'optimiz',
      'time to first token',
      'ttft',
      'cold start',
      'bottleneck',
    ],
  },
  {
    id: 'identity',
    label: 'Decentralized identity and privacy',
    short: 'Identity',
    definition: 'Credentials, key management, selective disclosure, and metadata leakage.',
    counts: 'Explaining what a credential scheme reveals to a verifier and what it hides.',
    doesNotCount: 'Asserting that a product is private, without a threat model.',
    keywords: [
      'wallet',
      'identity',
      'privacy',
      'anonymous',
      'credential',
      'authentication',
      'login',
      'decentralized identifier',
      'verifiable credential',
      'self-sovereign',
      'key management',
      'seed phrase',
      'selective disclosure',
      'attestation',
      'kyc',
      'privacy preserving',
      'metadata leak',
      'wallet recovery',
      'passkey',
    ],
  },
  {
    id: 'mechanism-design',
    label: 'Protocol economics and mechanism design',
    short: 'Incentives',
    definition: 'Incentives, fee markets, auctions, and how participants respond to them.',
    counts: 'Explaining how local fee markets stop one hot account pricing out a chain.',
    doesNotCount: 'Price commentary, market calls, or token predictions of any kind.',
    keywords: [
      'crypto',
      'token',
      'airdrop',
      'yield',
      'liquidity',
      'defi',
      'governance',
      'dao',
      'treasury',
      'reward',
      'emission',
      'validator reward',
      'incentive',
      'fee market',
      'auction',
      'mev',
      'tokenomics',
      'staking reward',
      'game theor',
      'mechanism design',
      'bonding curve',
      'slippage',
      'liquidity',
      'priority fee',
      'gas auction',
    ],
  },
  {
    id: 'creator-economy',
    label: 'Creator economy and distribution',
    short: 'Creator economy',
    definition: 'How work reaches an audience: publishing, distribution, and what creators earn.',
    counts: 'Explaining why a distribution channel changes what a creator can charge.',
    doesNotCount: 'Announcing a follower milestone.',
    keywords: [
      'creator','content creator','creator economy','distribution','audience','publishing',
      'monetiz','engagement','impressions','reach','newsletter','podcast','livestream',
      'sponsorship','brand deal','affiliate','subscriber','social graph','feed algorithm',
      'attention',
    ],
  },
  {
    id: 'prediction',
    label: 'Prediction and forecasting',
    short: 'Prediction',
    definition: 'Estimating what happens next, and the markets and models that price it.',
    counts: 'Explaining how a prediction market aggregates private information into a price.',
    doesNotCount: 'Posting a price target.',
    keywords: [
      'prediction','predictive','forecast','probability','odds','oracle','base rate',
      'calibration','prediction market','polymarket','estimator','signal','backtest',
      'expected value','confidence interval',
    ],
  },
  {
    id: 'payments',
    label: 'Payments and settlement',
    short: 'Payments',
    definition: 'Moving value: rails, stablecoins, settlement, payouts, and their costs.',
    counts: 'Explaining why settlement finality changes what a payout flow can promise.',
    doesNotCount: 'Announcing that a payment integration is live.',
    keywords: [
      'payment','payout','stablecoin','usdc','usdt','settlement','remittance','invoice',
      'checkout','merchant','fiat','on-ramp','off-ramp','payment rail','chargeback',
      'micropayment','escrow',
    ],
  },
  {
    id: 'sustainability',
    label: 'Sustainability and climate',
    short: 'Sustainability',
    definition: 'Energy, emissions, environmental measurement, and the systems that account for them.',
    counts: 'Explaining how a carbon credit is verified, and what makes the measurement contestable.',
    doesNotCount: 'Calling a product green with no measurement behind it.',
    keywords: [
      'sustainab','carbon','emission','climate','renewable','net zero','net-zero',
      'carbon credit','offset','esg','circular economy','biodiversity','reforest',
      'clean energy','solar','environmental','decarboniz','green tech',
    ],
  },
  {
    id: 'open-source',
    label: 'Open source and standards',
    short: 'Open source',
    definition: 'Specifications, interoperability, licensing, and maintenance practice.',
    counts: 'Explaining why a spec ambiguity produced two incompatible implementations.',
    doesNotCount: 'Announcing a release with no description of what changed.',
    keywords: [
      'contributor',
      'community',
      'grant',
      'hackathon',
      'bounty',
      'ecosystem',
      'builder',
      'launch',
      'open source',
      'open-source',
      'specification',
      'specification',
      'rfc',
      'standards body',
      'interoperab',
      'licensing',
      'maintainer',
      'upstream',
      'pull request',
      'changelog',
      'backward compat',
      'deprecat',
    ],
  },
] as const;

export const TOPIC_IDS: readonly string[] = TAXONOMY.map((t) => t.id);

export const isTopicId = (value: string): boolean => TOPIC_IDS.includes(value);

export const labelForTopic = (id: string): string =>
  TAXONOMY.find((t) => t.id === id)?.label ?? id;

/** For rows and cards, where a full label wraps or truncates. */
export const shortTopic = (id: string): string =>
  TAXONOMY.find((t) => t.id === id)?.short ?? id;
