/**
 * The seam between every task in this repository.
 *
 * FROZEN. Other agents are building against these shapes in parallel. If your task
 * appears to need one changed, stop and say so in your PR — do not edit this file.
 * See AGENTS.md.
 */

/**
 * One public post, normalized away from any provider's payload shape.
 *
 * Every engagement metric is `number | null`. `null` means the provider did not report
 * the value; it does NOT mean zero. Collapsing the two is a correctness bug that the
 * scoring module treats as materially different — a missing view count is not evidence
 * that nobody saw the post.
 */
export type Post = {
  id: string;
  text: string;
  /** ISO 8601. */
  createdAt: string;
  views: number | null;
  replies: number | null;
  reposts: number | null;
  likes: number | null;
  isReply: boolean;
  isRepost: boolean;
  isQuote: boolean;
};

/**
 * Why a fetch produced no posts.
 *
 * `invalid_handle`, `private`, and `empty` are ANSWERS, not failures: the provider did
 * its job and the answer is that there is nothing to analyze. They must never be retried
 * and never trigger a fallback to another provider — doing so burns quota to be told the
 * same true thing again.
 *
 * `provider` and `timeout` are failures. They may be retried once, and may fall through.
 */
export type ProviderErrorClass =
  | 'invalid_handle'
  | 'private'
  | 'empty'
  | 'provider'
  | 'timeout';

/**
 * A fetch outcome. Note the third arm: some providers collect asynchronously and hand
 * back a claim ticket instead of data. That is neither success nor failure, and modelling
 * it as either is what forces job queues into designs that do not need them.
 */
export type ProfileResult =
  | {
      ok: true;
      handle: string;
      displayName: string;
      followers: number | null;
      posts: Post[];
    }
  | { ok: false; errorClass: ProviderErrorClass }
  | { ok: false; pending: true; snapshotId: string };

export interface PostProvider {
  readonly name: 'brightdata' | 'twitterapi' | 'mock';
  /** Never throws. Every failure is a returned ProfileResult. */
  fetchRecentPosts(handle: string, limit: number): Promise<ProfileResult>;
  /** Only implemented by providers that collect asynchronously. */
  resolveSnapshot?(snapshotId: string): Promise<ProfileResult>;
}

/** Narrowing helpers, so call sites read as intent rather than shape-poking. */
export const isOk = (r: ProfileResult): r is Extract<ProfileResult, { ok: true }> => r.ok;
export const isPending = (
  r: ProfileResult,
): r is Extract<ProfileResult, { pending: true }> => !r.ok && 'pending' in r;
export const isFailure = (
  r: ProfileResult,
): r is Extract<ProfileResult, { errorClass: ProviderErrorClass }> =>
  !r.ok && 'errorClass' in r;

/** These three mean "nothing to analyze", not "something went wrong". Do not retry them. */
export const isAnswerNotFailure = (e: ProviderErrorClass): boolean =>
  e === 'invalid_handle' || e === 'private' || e === 'empty';
